add_newline = true
palette = "gruvbox"

[palettes.gruvbox]
dark_red = "#cc241d"
bright_red = "#fb4934"
dark_green = "#98971a"
bright_green = "#b8bb26"
dark_yellow = "#d79921"
bright_yellow = "#fabd2f"
dark_blue = "#458588"
bright_blue = "#83a598"
dark_purple = "#b16286"
bright_purple = "#d3869b"
dark_aqua = "#689d6a"
bright_aqua = "#8ec07c"
background = "#282828"
foreground = "#ebdbb2"

[[battery.display]]
threshold = 100
style = "bold bright_purple"

[username]
show_always = true
style_user = "bold bright_aqua"
style_root = "bold dark_red"


[character]
success_symbol = "[\\$](bold bright_aqua)"
error_symbol = "[\\$](bold dark_red)"

[git_status]
style = "bold bright_purple"

[git_branch]
style = "bold bright_yellow"
